#!/bin/bash

# Charge les modules nécessaires au projet
# à lancer avec ". load_modules" sinon les modules sont déchargés à la fin du script

module load llvm # opencv a besoin de libraries chargées indirectement ici
module load gcc/8 # gcc < 9 pour kokkos
module load cuda/11 # cuda 11 pour c++17
module load cmake # pour compiler kokkos et opencv
